# Generated by Django 4.2.7 on 2024-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0003_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
